services:
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    expose:
      - 3100
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki:/tmp
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/log/:/logs
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

networks:
  default:
    external: true
    name: traefik_default

volumes:
  loki:
    name: loki

